"""Emit the LaTeX result tables straight from the result CSVs.

Writing these by hand is how numbers drift between the data and the text, so
chapter 5 \\input{}s the files this script produces instead.
"""

import os

import numpy as np
import pandas as pd

THESIS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(THESIS, "results")
TEX = os.path.join(THESIS, "Bright_Wiredu_Nuakoh_Thesis_2023-24", "tables")
os.makedirs(TEX, exist_ok=True)

SHORT = {
    "Bicubic (classical)": "Bicubic",
    "Lanczos (classical)": "Lanczos",
    "FSRCNN (pretrained, SRCNN lineage)": "FSRCNN",
    "ESPCN (pretrained, SRCNN lineage)": "ESPCN",
    "ESRGAN (pretrained, x4 only)": "ESRGAN",
    "LSMAN (proposed)": "LSMAN (proposed)",
}


def write(name, body):
    path = os.path.join(TEX, name)
    with open(path, "w") as f:
        f.write(body)
    print("  wrote tables/" + name)


def bold_if(text, cond):
    return f"\\textbf{{{text}}}" if cond else text


# --------------------------------------------------------------------------
# natural-image benchmark
# --------------------------------------------------------------------------

def table_natural():
    df = pd.read_csv(os.path.join(RESULTS, "results_summary.csv"))
    df["m"] = df.model.map(SHORT)
    datasets = ["Set5", "Set14", "BSD100", "Urban100", "DIV2K-val"]

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[!ht]",
        "  \\centering",
        "  \\caption{Reconstruction accuracy on the natural-image benchmarks, "
        "reported as PSNR (dB) / SSIM on the luminance channel. Best result in "
        "each column in bold. ESRGAN is available only at $\\times 4$. "
        "Urban100 and DIV2K images are centre-cropped to a maximum side of 512 "
        "pixels, identically for every model.}",
        "  \\label{tab:natural}",
        "  \\small",
        "  \\begin{tabular}{@{}l" + "c" * len(datasets) + "@{}}",
        "    \\toprule",
        "    Method & " + " & ".join(datasets) + " \\\\",
        "    \\midrule",
    ]

    for scale in (2, 4):
        sub = df[df.scale == scale]
        lines.append(f"    \\multicolumn{{{len(datasets)+1}}}{{@{{}}l@{{}}}}"
                     f"{{\\emph{{Scale $\\times {scale}$}}}} \\\\")
        best = {d: sub[sub.dataset == d].psnr_db.max() for d in datasets}
        best_s = {d: sub[sub.dataset == d].ssim.max() for d in datasets}
        for m in ["Bicubic", "Lanczos", "FSRCNN", "ESPCN", "ESRGAN",
                  "LSMAN (proposed)"]:
            rows = sub[sub.m == m]
            if rows.empty:
                continue
            cells = []
            for d in datasets:
                r = rows[rows.dataset == d]
                if r.empty:
                    cells.append("--")
                    continue
                p, s = float(r.psnr_db.iloc[0]), float(r.ssim.iloc[0])
                cells.append(bold_if(f"{p:.2f}", np.isclose(p, best[d])) + " / " +
                             bold_if(f"{s:.4f}", np.isclose(s, best_s[d])))
            lines.append(f"    {m} & " + " & ".join(cells) + " \\\\")
        lines.append("    \\addlinespace")

    lines[-1] = "    \\bottomrule"
    lines += ["  \\end{tabular}", "\\end{table}", ""]
    write("tab_natural.tex", "\n".join(lines))


# --------------------------------------------------------------------------
# satellite benchmark
# --------------------------------------------------------------------------

def table_satellite():
    df = pd.read_csv(os.path.join(RESULTS, "results_satellite.csv"))
    order = ["Bicubic", "Lanczos", "FSRCNN", "ESPCN", "LSMAN (proposed)"]

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[!ht]",
        "  \\centering",
        "  \\caption{Reconstruction accuracy on 21 satellite tiles, reported as "
        "mean $\\pm$ standard deviation over the set. Metrics are computed on "
        "the luminance channel with a border of $s$ pixels shaved. Best result "
        "in each column in bold.}",
        "  \\label{tab:satellite}",
        "  \\small",
        "  \\begin{tabular}{@{}lcccc@{}}",
        "    \\toprule",
        "    & \\multicolumn{2}{c}{Scale $\\times 2$} "
        "& \\multicolumn{2}{c}{Scale $\\times 4$} \\\\",
        "    \\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "    Method & PSNR (dB) & SSIM & PSNR (dB) & SSIM \\\\",
        "    \\midrule",
    ]

    best = {(s, k): df[df.scale == s][k].max() for s in (2, 4)
            for k in ("psnr_db", "ssim")}

    for m in order:
        cells = []
        for s in (2, 4):
            r = df[(df.scale == s) & (df.model == m)]
            if r.empty:
                cells += ["--", "--"]
                continue
            p, ps = float(r.psnr_db.iloc[0]), float(r.psnr_std.iloc[0])
            v, vs = float(r.ssim.iloc[0]), float(r.ssim_std.iloc[0])
            cells.append(bold_if(f"{p:.2f} $\\pm$ {ps:.2f}",
                                 np.isclose(p, best[(s, 'psnr_db')])))
            cells.append(bold_if(f"{v:.4f} $\\pm$ {vs:.4f}",
                                 np.isclose(v, best[(s, 'ssim')])))
        lines.append(f"    {m} & " + " & ".join(cells) + " \\\\")

    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    write("tab_satellite.tex", "\n".join(lines))


# --------------------------------------------------------------------------
# efficiency
# --------------------------------------------------------------------------

def table_efficiency():
    df = pd.read_csv(os.path.join(RESULTS, "results_satellite.csv"))
    order = ["Bicubic", "Lanczos", "FSRCNN", "ESPCN", "LSMAN (proposed)"]
    params = {"Bicubic": "--", "Lanczos": "--", "FSRCNN": "$12$\\,K",
              "ESPCN": "$21$\\,K"}

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[!ht]",
        "  \\centering",
        "  \\caption{Model size and measured steady-state inference latency on "
        "a general-purpose CPU, for a single satellite tile. Warm-up iterations "
        "are excluded and each figure is the mean of ten runs. Parameter counts "
        "for FSRCNN and ESPCN are the published values.}",
        "  \\label{tab:efficiency}",
        "  \\small",
        "  \\begin{tabular}{@{}lccc@{}}",
        "    \\toprule",
        "    & & \\multicolumn{2}{c}{Latency (ms)} \\\\",
        "    \\cmidrule(lr){3-4}",
        "    Method & Parameters & $128 \\to 256$ & $64 \\to 256$ \\\\",
        "    \\midrule",
    ]

    for m in order:
        r2 = df[(df.scale == 2) & (df.model == m)]
        r4 = df[(df.scale == 4) & (df.model == m)]
        if m.startswith("LSMAN"):
            p = "$356$\\,K / $605$\\,K"
        else:
            p = params[m]
        l2 = f"{float(r2.latency_ms.iloc[0]):.1f}" if not r2.empty else "--"
        l4 = f"{float(r4.latency_ms.iloc[0]):.1f}" if not r4.empty else "--"
        lines.append(f"    {m} & {p} & {l2} & {l4} \\\\")

    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    write("tab_efficiency.tex", "\n".join(lines))


# --------------------------------------------------------------------------
# application: downstream land-use classification
# --------------------------------------------------------------------------

def wilson(p, n, z=1.96):
    """Wilson score interval -- reliable for proportions near 0 or 1, unlike
    the normal approximation."""
    d = 1 + z ** 2 / n
    centre = (p + z ** 2 / (2 * n)) / d
    half = z * np.sqrt(p * (1 - p) / n + z ** 2 / (4 * n ** 2)) / d
    return centre - half, centre + half


CONDITIONS = ["Native LR x2", "Bicubic x2", "LSMAN x2",
              "Native LR x4", "Bicubic x4", "LSMAN x4", "HR reference"]


def pretty(cond):
    """Condition name as it should appear in a table."""
    if cond == "HR reference":
        return "HR reference \\emph{(upper bound)}"
    kind, tag = cond.rsplit(" ", 1)
    if kind == "LSMAN":
        kind = "\\textbf{LSMAN}"
    return f"{kind} $\\times {tag.lstrip('x')}$"


def condition_rows(df, fmt, bold_best=None):
    """Emit one LaTeX row per condition, with a rule before the HR row."""
    lines = []
    best = {}
    if bold_best:
        sub = df[df.condition != "HR reference"]
        for col in bold_best:
            best[col] = sub[col].max()
    for cond in CONDITIONS:
        r = df[df.condition == cond]
        if r.empty:
            continue
        if cond == "HR reference":
            lines.append("    \\midrule")
        lines.append("    " + pretty(cond) + " & " + fmt(r.iloc[0], best) + " \\\\")
    return lines


def table_downstream():
    df = pd.read_csv(os.path.join(RESULTS, "results_downstream.csv"))
    n_test = int(df.n_test.iloc[0])

    def fmt(r, best):
        acc = f"{r.accuracy*100:.2f}"
        if "accuracy" in best and np.isclose(r.accuracy, best["accuracy"]):
            acc = f"\\textbf{{{acc}}}"
        return (f"{acc} & [{r.ci_lo*100:.1f}, {r.ci_hi*100:.1f}] "
                f"& {r.macro_f1:.3f}")

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[tbp]",
        "  \\centering",
        "  \\caption{Land-use classification accuracy on UC Merced. The feature "
        "extractor and the linear classifier are identical across conditions, "
        f"and the test set holds {n_test} images. Intervals are $95\\%$ Wilson "
        "score intervals. Best result among the reconstructions in bold.}",
        "  \\label{tab:downstream}",
        "  \\begin{tabular}{@{}lccc@{}}",
        "    \\toprule",
        "    Classifier input & Accuracy (\\%) & $95\\%$ interval & Macro-F1 \\\\",
        "    \\midrule",
    ]
    lines += condition_rows(df, fmt, bold_best=["accuracy"])
    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    write("tab_downstream.tex", "\n".join(lines))
    for _, r in df.iterrows():
        print(f"     {r.condition:<14} {r.accuracy*100:.2f}%")


def _table_downstream_legacy():
    df = pd.read_csv(os.path.join(RESULTS, "results_downstream.csv"))
    base = float(df[df.variant == "Bicubic"].accuracy.iloc[0])
    n_test = int(df.n_test.iloc[0])

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[tbp]",
        "  \\centering",
        "  \\caption{Land-use classification accuracy on UC Merced when the "
        "classifier is given each reconstruction of the same $\\times 4$ "
        "decimated input. The feature extractor and the linear classifier are "
        f"identical across rows, and the test set holds {n_test} images. "
        "Intervals are $95\\%$ Wilson score intervals. The three reconstructions "
        "overlap one another substantially and are not distinguishable at this "
        "sample size; only the high-resolution reference is separated from "
        "them.}",
        "  \\label{tab:downstream}",
        "  \\begin{tabular}{@{}lccc@{}}",
        "    \\toprule",
        "    Classifier input & Accuracy (\\%) & $95\\%$ interval "
        "& vs.\\ bicubic (pp) \\\\",
        "    \\midrule",
    ]
    for v in ["Native LR", "Bicubic", "LSMAN", "HR reference"]:
        r = df[df.variant == v]
        if r.empty:
            continue
        a = float(r.accuracy.iloc[0])
        lo, hi = wilson(a, n_test)
        name = {"LSMAN": "LSMAN (proposed)",
                "HR reference": "HR reference \\emph{(upper bound)}"}.get(v, v)
        d_s = "--" if v == "Bicubic" else f"${(a - base) * 100:+.2f}$"
        lines.append(f"    {name} & {a*100:.2f} & "
                     f"[{lo*100:.1f}, {hi*100:.1f}] & {d_s} \\\\")

    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    write("tab_downstream.tex", "\n".join(lines))

    for v in ["Bicubic", "LSMAN", "HR reference"]:
        a = float(df[df.variant == v].accuracy.iloc[0])
        lo, hi = wilson(a, n_test)
        print(f"     {v:<14} {a*100:.2f}%  [{lo*100:.1f}, {hi*100:.1f}]")


# --------------------------------------------------------------------------
# application: downlink budget and embedded deployment
# --------------------------------------------------------------------------

def table_bandwidth():
    df = pd.read_csv(os.path.join(RESULTS, "results_bandwidth.csv"))
    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[tbp]",
        "  \\centering",
        "  \\caption{Downlink budget. Volumes are measured as losslessly "
        "encoded bytes averaged over the 21 satellite tiles and scaled to a "
        "$10{,}000 \\times 10{,}000$ scene; transmission time assumes a "
        "$100$~Mbit/s payload downlink. Reconstruction quality is the "
        "corresponding LSMAN result from Table~\\ref{tab:satellite}.}",
        "  \\label{tab:bandwidth}",
        "  \\small",
        "  \\begin{tabular}{@{}lcccc@{}}",
        "    \\toprule",
        "    Transmission strategy & Scene (MB) & Reduction & Downlink (s) "
        "& PSNR / SSIM \\\\",
        "    \\midrule",
    ]
    for _, r in df.iterrows():
        q = "--" if np.isnan(r.psnr_db) else f"{r.psnr_db:.2f}\\,dB / {r.ssim:.3f}"
        red = "--" if r.scale == 1 else f"{r.png_reduction_pct:.1f}\\%"
        lines.append(f"    {r.strategy} & {r.scene_MB_png:.1f} & {red} "
                     f"& {r.downlink_s:.1f} & {q} \\\\")
    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    write("tab_bandwidth.tex", "\n".join(lines))


def table_deployment():
    df = pd.read_csv(os.path.join(RESULTS, "results_deployment.csv"))
    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[tbp]",
        "  \\centering",
        "  \\caption{TensorFlow Lite export. Sizes are the on-disk flatbuffer; "
        "latency is single-threaded interpreter time per tile on a "
        "general-purpose CPU, averaged over ten runs after warm-up.}",
        "  \\label{tab:deployment}",
        "  \\begin{tabular}{@{}lcccc@{}}",
        "    \\toprule",
        "    Scale & Precision & Tile & Model size & Latency (ms) \\\\",
        "    \\midrule",
    ]
    for _, r in df.iterrows():
        tile = r.input.replace("x", r" \times ")
        lines.append(f"    $\\times {int(r.scale)}$ & {r.precision} "
                     f"& ${tile}$ & {r.size_kb/1024:.2f}\\,MB "
                     f"& {r.latency_ms:.0f} \\\\")
    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    write("tab_deployment.tex", "\n".join(lines))


# --------------------------------------------------------------------------
# application: small-object identification
# --------------------------------------------------------------------------

def table_smallobjects():
    df = pd.read_csv(os.path.join(RESULTS, "results_smallobjects.csv"))
    bands = ["small", "medium", "large"]
    wide = df.pivot_table(index="condition", columns="band", values="accuracy")
    counts = df.drop_duplicates("band").set_index("band").n_test

    cuts_path = os.path.join(RESULTS, "smallobject_band_cuts.npy")
    if os.path.exists(cuts_path):
        c1, c2 = np.load(cuts_path)
        span = (f"Size groups are terciles of the object-size distribution: "
                f"below {c1:.0f}~px, {c1:.0f} to {c2:.0f}~px, and above "
                f"{c2:.0f}~px on the longest side in the high-resolution "
                f"reference. ")
    else:
        span = ""

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[tbp]",
        "  \\centering",
        "  \\caption{Object recognition accuracy (\\%) on NWPU VHR-10, grouped "
        "by object size. " + span +
        "Whole images are degraded and reconstructed before the annotated "
        "objects are cropped, so objects are corrupted as they would be in a "
        "real acquisition. Best result among the reconstructions in each "
        "column in bold.}",
        "  \\label{tab:smallobjects}",
        "  \\begin{tabular}{@{}lcccc@{}}",
        "    \\toprule",
        "    & \\multicolumn{3}{c}{By object size} & \\\\",
        "    \\cmidrule(lr){2-4}",
        "    Classifier input & small & medium & large & all \\\\",
        "    \\midrule",
    ]

    sub = wide.drop(index="HR reference", errors="ignore")
    best = {b: sub[b].max() for b in bands if b in sub}
    all_col = df[df.band == "all"].set_index("condition").accuracy
    best_all = all_col.drop(index="HR reference", errors="ignore").max()

    for cond in CONDITIONS:
        if cond not in wide.index:
            continue
        if cond == "HR reference":
            lines.append("    \\midrule")
        cells = []
        for b in bands:
            v = wide.loc[cond, b] if b in wide.columns else np.nan
            s = "--" if np.isnan(v) else f"{v*100:.2f}"
            if not np.isnan(v) and b in best and np.isclose(v, best[b]):
                s = f"\\textbf{{{s}}}"
            cells.append(s)
        a = all_col.get(cond, np.nan)
        s = "--" if np.isnan(a) else f"{a*100:.2f}"
        if not np.isnan(a) and np.isclose(a, best_all):
            s = f"\\textbf{{{s}}}"
        cells.append(s)
        lines.append("    " + pretty(cond) + " & " + " & ".join(cells) + " \\\\")

    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    write("tab_smallobjects.tex", "\n".join(lines))
    print("     objects per band:",
          {b: int(counts.get(b, 0)) for b in bands})


# --------------------------------------------------------------------------
# application: asset change tracking
# --------------------------------------------------------------------------

def table_changedetection():
    df = pd.read_csv(os.path.join(RESULTS, "results_changedetection.csv"))

    def fmt(r, best):
        f1 = f"{r.f1:.3f}"
        if "f1" in best and np.isclose(r.f1, best["f1"]):
            f1 = f"\\textbf{{{f1}}}"
        return f"{r.precision:.3f} & {r.recall:.3f} & {f1}"

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[tbp]",
        "  \\centering",
        "  \\caption{Building-change detection on LEVIR-CD. Both dates are "
        "degraded and reconstructed identically, and the classifier receives "
        "the absolute difference of their features. Roughly a third of the "
        "patches contain change, so F1 is reported alongside its components "
        "rather than accuracy alone. Best result among the reconstructions in "
        "bold.}",
        "  \\label{tab:changedetection}",
        "  \\begin{tabular}{@{}lccc@{}}",
        "    \\toprule",
        "    Detector input & Precision & Recall & F1 \\\\",
        "    \\midrule",
    ]
    lines += condition_rows(df, fmt, bold_best=["f1"])
    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    write("tab_changedetection.tex", "\n".join(lines))


# --------------------------------------------------------------------------
# application: agricultural parcels and canopies
# --------------------------------------------------------------------------

def table_agriculture():
    df = pd.read_csv(os.path.join(RESULTS, "results_agriculture.csv"))

    def fmt(r, best):
        cells = []
        for col, spec in (("boundary_f1", "{:.3f}"), ("parcel_iou", "{:.3f}"),
                          ("canopy_f1", "{:.3f}")):
            s = spec.format(r[col])
            if col in best and np.isclose(r[col], best[col]):
                s = f"\\textbf{{{s}}}"
            cells.append(s)
        err = f"{r.count_error*100:.1f}"
        if "count_error" in best and np.isclose(r.count_error, best["count_error"]):
            err = f"\\textbf{{{err}}}"
        cells.append(err)
        return " & ".join(cells)

    sub = df[df.condition != "HR reference"]
    best = {c: sub[c].max() for c in ("boundary_f1", "parcel_iou", "canopy_f1")}
    best["count_error"] = sub.count_error.min()

    lines = [
        "% generated by scripts/make_tables.py -- do not edit by hand",
        "\\begin{table}[tbp]",
        "  \\centering",
        "  \\caption{Agricultural parcel delineation and canopy counting on the "
        f"{int(df.n_tiles.iloc[0])} satellite tiles. The reference is derived "
        "from the high-resolution image by the same fixed procedure applied to "
        "every condition, so the measure is agreement with full-resolution "
        "extraction rather than accuracy against field survey. Best result "
        "among the reconstructions in bold.}",
        "  \\label{tab:agriculture}",
        "  \\small",
        "  \\begin{tabular}{@{}lcccc@{}}",
        "    \\toprule",
        "    & \\multicolumn{2}{c}{Parcel delineation} "
        "& \\multicolumn{2}{c}{Canopy counting} \\\\",
        "    \\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
        "    Input & Boundary F1 & Parcel IoU & Match F1 & Count error (\\%) \\\\",
        "    \\midrule",
    ]
    for cond in CONDITIONS:
        r = df[df.condition == cond]
        if r.empty:
            continue
        if cond == "HR reference":
            lines.append("    \\midrule")
        lines.append("    " + pretty(cond) + " & " + fmt(r.iloc[0], best) + " \\\\")
    lines += ["    \\bottomrule", "  \\end{tabular}", "\\end{table}", ""]
    write("tab_agriculture.tex", "\n".join(lines))


if __name__ == "__main__":
    print("writing tables to", TEX)
    table_natural()
    table_satellite()
    table_efficiency()
    for fn in (table_downstream, table_smallobjects, table_changedetection,
               table_agriculture, table_bandwidth, table_deployment):
        try:
            fn()
        except FileNotFoundError as e:
            print(f"  skipped {fn.__name__}: {os.path.basename(str(e).split()[-1])} missing")
